environment:

  matrix:
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7.11"
      TESTENVS: "py27-pyqt4"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %APPVEYOR_REPO_TAG_NAME%"

install:
  # dump version
  - git describe --tags --always
  # install and build Lua and the lupa python module
  - git clone https://github.com/LuaDist/lua.git
  - git -C lua describe --tags --always
  - mkdir lua-build
  - cd lua-build
  - "\"%LOCALAPPDATA%\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\vcvarsall.bat\" x86"
  - cmake -G "NMake Makefiles" ../lua
  - nmake
  - cd ..
  - ps: "iwr https://raw.githubusercontent.com/mattn/gntp-send/master/include/msinttypes/stdint.h -OutFile \".\\lua-build\\stdint.h\""
  - "%PYTHON%\\Scripts\\pip install --global-option=build_ext --global-option=\"-I%APPVEYOR_BUILD_FOLDER%\\lua-build;%APPVEYOR_BUILD_FOLDER%\\lua\\src\" --global-option=\"-L%APPVEYOR_BUILD_FOLDER%\\lua-build\" --global-option=\"-lliblua_static\" lupa"
  # install dependencies using pip
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt --trusted-host content.faforever.com"
  - ps: "$env:APPVEYOR_BUILD_VERSION = (& C:\\Miniconda\\python .\\src\\config\\version.py) + \"+\" + $env:APPVEYOR_BUILD_NUMBER"
  - ps: "get-childitem env:"
  - "%PYTHON%\\python setup.py bdist_msi"

artifacts:
  - path: '**\*.msi'

deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    auth_token:
      secure: "09WRxoB8lu9lPzuk3qYu0brKVQubLpnsS1Wdn49nYZYi5RDiva3z37eITcjtZkTD"
    artifact: /.*\.msi/
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: true

build: off
